// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Utils$ReactTemplate = require("./utils.bs.js");

function Credit(Props) {
  var value = Props.value;
  return React.createElement("div", undefined, Utils$ReactTemplate.rs("You have "), Utils$ReactTemplate.rs(value.toFixed(2)), Utils$ReactTemplate.rs("€"));
}

var make = Credit;

exports.make = make;
/* react Not a pure module */
