// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Credit$ReactTemplate = require("./Credit.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Credit$ReactTemplate.make, {
          value: 1.5
        }), "index1");

/*  Not a pure module */
